version: '3.10'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    restart: unless-stopped
    env_file:
      - ../.env

  # 컬렉션 체크 및 생성 스크립트 실행용 Python 컨테이너
  collection-init:
    image: python:3.10
    container_name: collection-init-container
    depends_on:
      - mongodb  # MongoDB가 실행된 후에 이 컨테이너가 실행됨
    volumes:
      - ./scripts:/scripts  # 스크립트가 있는 폴더
    command: >
      bash -c "
      pip install pymongo;
      python3 /scripts/initialize_collections.py;
      echo '컬렉션 체크 및 생성 작업 완료';
      "
    env_file:
      - ../.env

volumes:
  mongodb_data:
